[package]
name = "evoimage"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
log = "0.4.22"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
simple_logger = "5.0.0"
